name: Ahsa 6 hours workflow

on:
  1schedule:
    - cron: "0 */6 * * *"  # Har 6 ghante run hoga
  workflow_dispatch:        # Optional: manual run ka option bhi rahe

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: echo "Yeh har 6 ghante run ho raha hai"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: |
          echo "Bot starting..."
          node index.js
