name: Auto Run Bot Every 5h40m

on:
  schedule:
    # Har 5h40m ke interval ka cron (poore din repeat hoga)
    - cron: '0 0 * * *'
    - cron: '50 5 * * *'
    - cron: '40 11 * * *'
    - cron: '30 17 * * *'
    - cron: '20 23 * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: |
          echo "Bot starting..."
          node index.js
